### ISSUE TITLE
在安卓5.1上不显示火焰图

### ISSUE THREAD

**Issue by chfdeng** [Knight-ZXW/BlockCanaryX#10]
应该是5.1上不支持es6的标准，所以无法显示，请问这个可否支持呢

**Comment by Knight-ZXW** [comment]
今天支持下

**Comment by Knight-ZXW** [comment]
你用的 是0.0.5版本吗，

**Comment by chfdeng** [comment]
是的，更新了0.0.5

**Comment by chfdeng** [comment]
使用了在线工具将js的代码转换成es5的，好像也不行，然后替换了腾讯x5内核就可以了，不过又得额外引入，所以要是你可以改那些js代码就最好了

**Comment by Knight-ZXW** [comment]
> 使用了在线工具将js的代码转换成es5的，好像也不行，然后替换了腾讯x5内核就可以了，不过又得额外引入，所以要是你可以改那些js代码就最好了

你是用真机测试的吗

**Comment by chfdeng** [comment]
是的

**Comment by Knight-ZXW** [comment]
> 是的，更新了0.0.5

0.0.5  是今天下午 才更新到 maven central 的，你之前确定用的0.0.5吗

**Comment by chfdeng** [comment]
我不是用的你的包，是用源码集成，在android11上正常，在android5.1不显示，然后今天下午看到了你5天前提交的[修复低版本浏览器的兼容性问题]这个修改，就两个js文件，我把这两个文件更新了，在android5.1上还是显示不出来
