### ISSUE TITLE
无法通过gradle依赖

### ISSUE THREAD

**Issue by mm46468648** [Knight-ZXW/BlockCanaryX#11]
找不到这个库。还应该添加什么配置么

**Comment by mm46468648** [comment]
无法找到依赖库，编译不通过

**Comment by Knight-ZXW** [comment]
贴下您的报错信息，
这个库是上传到mavenCentral上的，只有有添加         mavenCentral() ，一般就能搜索到。

**Comment by Knight-ZXW** [comment]
你是 使用0.0.5版本吗 ， 0.0.5 我忘记传maven了，刚传上去，预计等待一个小时

**Comment by Knight-ZXW** [comment]
已更新，再试下 0.0.5

**Comment by liangchaojie** [comment]
老哥方便加个微信不，想一起学习丰富你的库    wx:    Gerry_Liang_F

**Comment by liangchaojie** [comment]
> 老哥方便加个微信不，想一起学习丰富你的库 wx: Gerry_Liang_F

@Knight-ZXW

**Comment by Knight-ZXW** [comment]
> > 老哥方便加个微信不，想一起学习丰富你的库 wx: Gerry_Liang_F
> 
> @Knight-ZXW
这个账号就是我的微信号 kngiht-zxw
