### ISSUE TITLE
这个库可以带上网络权限<uses-permission-sdk-23 android:name="android.permission.INTERNET"/>

### ISSUE THREAD

**Issue by liangchaojie** [Knight-ZXW/BlockCanaryX#12]
如果不加的话, 无法打开网页。

**Comment by liangchaojie** [comment]
另外提一个建议:  WebView火焰图页面可以增加返回键,  大部分手机上都有物理返回键，但是在一些车机系统上不支持返回，只能home.

**Comment by Knight-ZXW** [comment]
> 另外提一个建议: WebView火焰图页面可以增加返回键, 大部分手机上都有物理返回键，但是在一些车机系统上不支持返回，只能home.

有时间的话，您这边可以提个MR吗

**Comment by liangchaojie** [comment]
> > 另外提一个建议: WebView火焰图页面可以增加返回键, 大部分手机上都有物理返回键，但是在一些车机系统上不支持返回，只能home.
> 
> 有时间的话，您这边可以提个MR吗

**Comment by liangchaojie** [comment]
> > 另外提一个建议: WebView火焰图页面可以增加返回键, 大部分手机上都有物理返回键，但是在一些车机系统上不支持返回，只能home.
> 
> 有时间的话，您这边可以提个MR吗

OK 可以的
