### ISSUE TITLE
Failed to resolve: io.github.knight-zxw:blockcanary:0.05

### ISSUE THREAD

**Issue by feng612266** [Knight-ZXW/BlockCanaryX#22]
Failed to resolve: io.github.knight-zxw:blockcanary:0.05，maven { url 'https://repo1.maven.org/maven2/'} had added

**Comment by Knight-ZXW** [comment]
implementation 'io.github.knight-zxw:blockcanary-ui:0.0.5'

https://repo1.maven.org/maven2/io/github/knight-zxw/blockcanary/0.0.5/

**Comment by feng612266** [comment]
//引入卡顿监控实现依赖库
    //implementation 'io.github.knight-zxw:blockcanary:0.05'
    //引入卡顿消息通知及相关展示UI
    implementation 'io.github.knight-zxw:blockcanary-ui:0.05'
    // 如果你只想在debug包引入，不希望被引入release包，可以使用 debugImplementation
    //debugImplementation 'io.github.knight-zxw:blockcanary:0.05'      Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.github.knight-zxw:blockcanary-ui:0.05.
other library is normal

**Comment by feng612266** [comment]
> ```
> //引入卡顿监控实现依赖库
> //implementation 'io.github.knight-zxw:blockcanary:0.05'
> //引入卡顿消息通知及相关展示UI
> implementation 'io.github.knight-zxw:blockcanary-ui:0.05'
> // 如果你只想在debug包引入，不希望被引入release包，可以使用 debugImplementation
> //debugImplementation 'io.github.knight-zxw:blockcanary:0.05'      Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.github.knight-zxw:blockcanary-ui:0.05.
> ```
> 
> other library is normal

try use 0.04 is also can not found

**Comment by feng612266** [comment]
> > ```
> > //引入卡顿监控实现依赖库
> > //implementation 'io.github.knight-zxw:blockcanary:0.05'
> > //引入卡顿消息通知及相关展示UI
> > implementation 'io.github.knight-zxw:blockcanary-ui:0.05'
> > // 如果你只想在debug包引入，不希望被引入release包，可以使用 debugImplementation
> > //debugImplementation 'io.github.knight-zxw:blockcanary:0.05'      Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find io.github.knight-zxw:blockcanary-ui:0.05.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > other library is normal
> 
> try use 0.04 is also can not found
allprojects {
    repositories {
        maven {url 'https://maven.aliyun.com/nexus/content/repositories/releases/'}
        maven {url 'https://developer.huawei.com/repo/'}
        maven {url 'https://maven.aliyun.com/repository/central/'}
        maven {url 'https://maven.aliyun.com/repository/public/'}
//        maven {url 'https://maven.aliyun.com/repository/google/'}
//        maven {url 'https://maven.aliyun.com/repository/gradle-plugin/'}
        maven { url "https://jitpack.io" }
        maven { url 'https://repo1.maven.org/maven2/'}
        google()
    }
