### ISSUE TITLE
android 8.1系统有问题

### ISSUE THREAD

**Issue by gegeName** [Knight-ZXW/BlockCanaryX#4]
在android8.1系统中，点击进入webView查看耗时ui里面是一片空白，什么也没有
[
![215C722A6E8A73DD32ECB705EDA1C450](https://user-images.githubusercontent.com/20966610/178895248-8605119a-dcf8-4817-bb3a-c3b464a80685.jpg)
](url)

**Comment by Knight-ZXW** [comment]
是不是和 #7 一样的问题，可以试试0.0.4版本

**Comment by Knight-ZXW** [comment]
应该是 低版本浏览器的兼容性问题，已修复
