### ISSUE TITLE
Builder.class  blockMaxThresholdTime 改变不生效

### ISSUE THREAD

**Issue by lida812699070** [Knight-ZXW/BlockCanaryX#8]
初始化是通过startUp去初始化的  在Application#onCreate之前 BlockCanaryInternal#install判断了不会重复初始化   所以在application oncreate初始化其实并不生效

**Comment by Knight-ZXW** [comment]
> 初始化是通过startUp去初始化的 在Application#onCreate之前 BlockCanaryInternal#install判断了不会重复初始化 所以在application oncreate初始化其实并不生效

使用startup 库初始化的功能是可以关闭， 在Demo模块我忘记关了， 后面我修改下 [这里的配置](https://github.com/Knight-ZXW/BlockCanaryX/blob/main/app/src/main/res/values/my_block_canary.xml)
