### ISSUE TITLE
模拟器看不到火焰图

### ISSUE THREAD

**Issue by Beta116Beta** [Knight-ZXW/BlockCanaryX#9]
用的逍遥游模拟器
![image](https://user-images.githubusercontent.com/93580411/224702436-f124d7b9-5bb7-4ea3-93b9-1963d0f9ae9c.png)

**Comment by Knight-ZXW** [comment]
看下 logcat 有什么异常日志输出吗

**Comment by Beta116Beta** [comment]
在真机上的可以看到的，就模拟器不行，用真机看就好了

**Comment by Knight-ZXW** [comment]
模拟器问题的话 ，晚上我测试下，公司没windows环境

**Comment by Knight-ZXW** [comment]
已修复，模拟器测试通过， 更新到 0.0.5版本就行

![image](https://user-images.githubusercontent.com/11730925/225657685-6fa09688-774b-4f9d-b7bc-dd529713a159.png)
